### ISSUE TITLE
Add a very simple example

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#108]
^^^^^^^^

**Comment by ardunn** [comment]
This should be a notebook or .py file predicting a target property. It can literally be something along these lines (and should include a test making sure the notebook works with each build). The number of lines of code should be about 10-20 (very short)

```python
from automatminer.pipe import MatPipe, default_config
from matminer.datasets.dataset_retrieval import load_dataset
from sklearn.metrics import r2_score

df = load_dataset("elastic_tensor_2015")
pipe = MatPipe(**default_config)

df = df.rename(columns={"formula": "composition})["composition", "structure", "K_VRH"]
predicted = pipe.benchmark(df, "K_VRH", test_spec=0.2)

y_true = predicted["K_VRH"]
y_test = predicted["K_VRH predicted"]
print(r2_score(y_true, y_test))
```
The explanations should be longer. The example should be up to good data science standards (i.e., don't just use R2 here like I do, use MSE). The example should be brief but complete

**Comment by ADA110** [comment]
Has the change to get_present_config been completely pushed, or is it still a work in progress? I'd imagine that I would need to replace default_config with the new tools

**Comment by ardunn** [comment]
@ADA110 pretty much completely pushed.
