### ISSUE TITLE
Empty logger made anytime MatPipe imported

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#141]

**Comment by ADA110** [comment]
https://www.benkuhn.net/importtime

**Comment by ardunn** [comment]
got it, didn't even realize that was outside of an `if __name__=="__main__" block. im trying to think of some ways we can still import these configs without having these unnecessary .logs and also without making it overly complicated. perhaps we can just convert them to functions (which return the dicts shown)? Or if you have another idea I'm all ears

**Comment by ardunn** [comment]
closed via 9e809c87f6ae522039250b23956eab65edfdab4a
