### ISSUE TITLE
 No module named 'automatminer.featurize'

### ISSUE THREAD

**Issue by theiman112860** [hackingmaterials/automatminer#146]
Hi,

I installed automatminer via pip install -e (location where I unzipped it) and tried to run the following:

from automatminer.featurize import Featurize  and got:

        ModuleNotFoundError                       Traceback (most recent call last)
        <ipython-input-8-77e63ad90aaf> in <module>()
         ----> 1 from automatminer.featurize import Featurize

        ModuleNotFoundError: No module named 'automatminer.featurize'

I then tried to run:
from automatminer.preprocess import Preprocess and got:

        ---------------------------------------------------------------------------
       ModuleNotFoundError                       Traceback (most recent call last)
       <ipython-input-9-7522b8d91623> in <module>()
        ----> 1 from automatminer.preprocess import PreProcess

        ModuleNotFoundError: No module named 'automatminer.preprocess'

Any ideas on what I did or did not do correctly?  Thank you!

Sincerely,

tom

**Comment by ardunn** [comment]
Hey tom,

If you are trying to run the notebooks/examples, that is because they are are woefully out of date. We’ll be updating them soon, stay tuned...

In the meantime, you should be able to access the MatPipe object by doing ‘from auto matminer.pipeline import MatPipe’. This class will allow you to do 95% of what you can do with automatminer

**Comment by ardunn** [comment]
Hi tom, 

If you are trying to benchmark how well MatPipe does on a given dataset (i.e., get a dataframe back with predictions on a held test set, which you can then look at), do the following:

```python
from automatminer.pipeline import MatPipe

# Get back a df containing 20% of your data held as a test set, + predictions
predicted_df = pipe.benchmark(df, "your_target_property_column", test_spec=0.2)
```

If you want to predict on out-of-sample data (i.e., make some predictions on new materials), do the following:

```python
pipe = MatPipe()
pipe.fit(df, "your_target_property_column")

# Get back predictions made on another df
predicted_df = pipe.predict(some_other_df, "your_target_property_column")
```

If you want to use structure features, you must have a column called "structure" containing pymatgen Structure objects. If you want to use composition features, you must have a column called "composition".

Also a general heads up: this code is still in early development. We'll be making some more complete tutorials in the near future :)

**Comment by theiman112860** [comment]
Hi Ardunn,
Thank you!  What I wanted to do is to add both compositional and structural features to my dataframe..
Sincerely,
tom

**Comment by ardunn** [comment]
in that case, make sure you have both “composition” and “structure” columns in your dataframe

**Comment by theiman112860** [comment]
Hi Alex,
Thank you!!  Will do!
Sincerely,
tom

-----Original Message-----
