### ISSUE TITLE
Add random_state option to benchmark function

### ISSUE THREAD

**Issue by utf** [hackingmaterials/automatminer#160]
Would be nice to add support for the `random_sample` variable of `pandas.DataFrame.sample()` for pipeline benchmarking.

E.g. implemented for this line:

```
testdf, traindf = np.split(df.sample(frac=1), [int(test_spec * len(df))])
```

Would allow for random but deterministic sampling of the dataframe when choosing the test/train split. This way you can benchmark two models on the same dataframe and automatically have the same test/train split. Can just override the benchmark `test_spec` variable again (e.g. if `test_spec` is an int or `numpy.random.RandomState` object then use it as the `random_sample` variable).

**Comment by ardunn** [comment]
sounds good to me!

**Comment by ardunn** [comment]
@utf current benchmarking implementation has you pass in a sklearn kfold (or StratifiedKFold) to the benchmarking function. the kfold object can accept a random state param, so this issue is essentially closed.
