### ISSUE TITLE
General problem: Featurization takes too long!

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#179]
Featurizing all of MP takes at least one day. This is way, way too long.

Edit:
Easiest way to fix this is by:
- [x] Converting all featurizers over to inplace=False
- [x] ability to just cache dfs

**Comment by utf** [comment]
Do you know what is taking the most time?

**Comment by ardunn** [comment]
@utf Structure featurization.

**Comment by utf** [comment]
Is it SiteStatsFeaturizer (with CrystalNN preset) or something else?

**Comment by ardunn** [comment]
To featurize 83k structures, it is taking roughly 12+ hours on beefy lawrencium Xeon compute nodes.

**Comment by ardunn** [comment]
It is many of them. SiteStatsFeaturizer is among the worst offenders

**Comment by ardunn** [comment]
Try featurizing elastic tensor dataset with the autofeaturizer "best" preset and see for yourself.

**Comment by utf** [comment]
It could be that we keep recalculating the bonding which takes a long time for big structures.

We could check by seeing if there is a big speed up using MultipleFeaturizer with the additional caching. This is not a long term solution though, as we would then lose a lot of the fidelity of timing per featurizer.

If calculating the bonding is taking the most amount of time, we could alter the featurizers to also accept a BondedStructure object, in which case the bonding would not be recalculated. And then just have a StructureToBondedStructure conversion featurizer.

**Comment by ardunn** [comment]
So that is one problem. Another problem is that it is just too slow for even one SiteStatsFingerprint for many large structures. For example running it on MP towards the larger structures I get times of ~1s/sample (running on a LR4 node on Lawrencium). As far as I can tell, it is running in fully parallel mode (n_jobs  = cput_count() = 24)...

**Comment by ardunn** [comment]
After looking into this, not sure caching actually really improves the performance (or maybe I am just using wrong?)

**Comment by ardunn** [comment]
done via 7f4f99e3c0f717b236b6373e01a130da5969b618
