### ISSUE TITLE
The .git folder is absolutely enormous. 

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#189]
```
$ du -sh .git
 54M	.git
```

**Comment by ardunn** [comment]
The rest of the package combined is less than 5MB.

**Comment by utf** [comment]
This is an easy fix with https://rtyley.github.io/bfg-repo-cleaner/

I already did this but I never merged and the package has moved along quite a bit. It would probably require all contributors to reclone the repo after cleaning is done.

**Comment by ardunn** [comment]
Ok maybe we can do this once I finish all the priority issues on here. I'll ping u again once that is done
