### ISSUE TITLE
setup.py imports automatminer 

### ISSUE THREAD

**Issue by utf** [hackingmaterials/automatminer#202]
setup.py  import automatminer. If automatminer has not be installed before, then this step can fail.

**Comment by ardunn** [comment]
@utf weird that this is happening, did it throw error for you?

i changed it regardless but still

In the python docs they reference it as a legitimate method of single-source versioning but with a warning. i haven't run into any problems with it but still

https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by utf** [comment]
The reason why this failed and that the example works, is because we are importing other things in the root __init__.py file. So I was getting an error that xgboost wasn't installed when I was trying to pip install automatminer to install the new dependencies. 

You could use your old method for versioning, provided `import automatminer` doesn't import any external packages.
