### ISSUE TITLE
Enforce a code style

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#208]
e.g., black formatting. 

https://github.com/python/black

**Comment by janosh** [comment]
I can recommend `black` in conjunction with [`flake8`](http://flake8.pycqa.org/en/latest) which would do the style enforcing. For instance, this is the config I use (specified in `setup.cfg`):

```cfg
[flake8]
max-line-length = 100
exclude = .git
# E731: do not assign a lambda expression, use a def
# W293: blank line contains whitespace
# E203: whitespace before ':'
# E265: block comment should start with '# '
# W503: line break before binary operator
ignore = E203, E731, W293, E265, W503

# make isort play nicely with black's import formatting
# https://github.com/microsoft/vscode-python/issues/5840
[isort]
multi_line_output = 3
include_trailing_comma = True
```

**Comment by utf** [comment]
I think using black is a great idea. I'm not sure about some of those exceptions though. Particularly, it seems useful to have checks for these:

```
# W293: blank line contains whitespace
# E203: whitespace before ':'
# E265: block comment should start with '# '
# W503: line break before binary operator
```

**Comment by janosh** [comment]
@utf Sure, I just copied those over from another project where they accumulated over time to act as an example.
