### ISSUE TITLE
Update xgboost version to 0.80

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#210]
Pip installations of xgboost 0.72 on windows platforms are troublesome.

**Comment by computron** [comment]
closed via 	63a4df92062600fd8e17d5a033a5a4429928a109

I think it took less time to close this issue than it probably did to open it?

**Comment by ardunn** [comment]
@computron thx

wasn't sure if anything would break. the circleci tests are not complete unless you run the "intensive" tests (/run_intensive.sh). i will run them now and see if all is good

**Comment by ardunn** [comment]
update: all is well
