### ISSUE TITLE
Cannot rebuild docs?

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#213]
@samysspace are you able to build the docs? When I `invoke make-doc` now, I get:

```
Exception occurred:
  File "/Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 274, in automodapi_replace
    app.warn(msg, location)
AttributeError: 'Sphinx' object has no attribute 'warn'
```

I think it has something to do with this sphinx_automodapi package needed for generating the API docs...

**Comment by samysspace** [comment]
Hmm, it seems to be working just fine on my end. I might be working off of a slightly different version of the repo though. I'm going to reset my repo and get back to you.

**Comment by ardunn** [comment]
What sphinx and sphinx-automodapi versions are you using?

**Comment by samysspace** [comment]
I use the latest versions for both. I fetched a fresh copy of the repository and the build still works for me. Is sphinx-automodapi installed on your environment?
<img width="579" alt="Screen Shot 2019-05-14 at 9 51 11 PM" src="https://user-images.githubusercontent.com/9342039/57749350-84fd3400-7692-11e9-84f1-bc6ab970a475.png">

**Comment by ardunn** [comment]
Im also using both the latest versions on python 3.7.3. Puzzling...
