### ISSUE TITLE
Add warning for mismatched versions of automatminer on save/load

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#230]
Saving should keep the pipeline with a version attribute. Upon loading, the version should be checked against the current version. If they are not matching, throw warning or error.

**Comment by kauziishere** [comment]
There's already version_check in automatminer/featurization/core.py, Do we need to just use that function in load model?

**Comment by ardunn** [comment]
@kauziishere there is...? I don't see it in current master branch
