### ISSUE TITLE
Add CI for python 3.6

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#259]

**Comment by janosh** [comment]
[Discussed here](https://github.com/hackingmaterials/automatminer/issues/253#issuecomment-545560652).

**Comment by ardunn** [comment]
@janosh I've added CI for python 3.6.7 and the quick tests are passing at least, so it might be worth trying on your 3.6 installation again. If you are still having problems we'll need to add a minimal unittest for it. 

Also, I'd recommend upgrading to the new amm version (which I'll release in the next few days) as a lot of the latent memory issues (i.e., random segfaults) have been fixed
