### ISSUE TITLE
Keyword arg for predicted column name

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/automatminer#266]
The default name `target + " predicted"` for the new column appended to a dataframe by `mat_pipe.predict()` contains a space and prevents the use of dot notation to access the column. Would you accept a PR to make this suffix configurable or maybe even change the default to `target + _predicted"` or `target + _pred"`?

**Comment by ardunn** [comment]
Hey @janosh I'd accept a PR to make it configurable!

I think this should take form in two parts: 
(1) a default arg to the base class DFMLAdaptor and 
(2) a powerup kwarg to the get_preset_config for MatPipe.from_preset method.

**Comment by janosh** [comment]
Are you sure this should be part of `get_preset_config()`? Seems too unimportant to make it part of a preset.

**Comment by ardunn** [comment]
Yes, in the sense it should be a powerup (kwarg), not a preset itself. The "powerups" are intended to be common options that are applied to the pre-defined presets. The idea is that if you want to enable some common options while using a preset (e.g., cache the features in some file, set the number of jobs, etc.) you don't need to specify an entire custom pipeline for MatPipe.

For example, `n_jobs` is a powerup which can be applied to any of the presets to define the number of jobs for featurization and learning across the entire pipeline. Similarly, the `target_output_col` (or whatever name) could be a powerup which sets the output col name. 

So without making it a powerup, if you wanted to set the output col name, you'd need to either define and entire custom pipeline (bad, lots of work [relatively]) or get the preset config and then replace the AutoFeaturizer with a custom one (less bad, but still not intuitive).

Making it a powerup in `get_preset_config`, you could just:
```
pipe = MatPipe.from_preset("express", target_output_col="custom column name")
```

**Comment by janosh** [comment]
I see what you mean. I'll add that.
